version: "3.8"

services:
  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "3000:3000"
    environment:
      - VITE_SERVER=http://localhost:8080
    networks:
      - mern
    depends_on:
      - backend

  backend:
    build: ./backend
    container_name: backend
    ports:
      - "8080:8080"
    environment:
      - PORT=${PORT}
      - DB=${DB}
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - GOOGLE_CALLBACK_URL=${GOOGLE_CALLBACK_URL}
      - JWT_SECRET=${JWT_SECRET}
      - STRIPE_SECRET_KEY=${STRIPE_SECRET_KEY}
      - FRONTEND=${FRONTEND}
      - NODE_ENV=${NODE_ENV}
      - RAZORPAY_SECRET_KEY=${RAZORPAY_SECRET_KEY}
      - RAZORPAY_KEY_ID=${RAZORPAY_KEY_ID}
      - EMAIL_USER=${EMAIL_USER}
      - EMAIL_PASS=${EMAIL_PASS}
      - CLOUDINARY_NAME=${CLOUDINARY_NAME}
      - CLOUDINARY_API_KEY=${CLOUDINARY_API_KEY}
      - CLOUDINARY_SECRET_API_KEY=${CLOUDINARY_SECRET_API_KEY}
      - CLIENT_URL=http://localhost:3000
    networks:
      - mern
    volumes:
      - ./backend:/app
      - /app/node_modules
    env_file:
      - ./backend/.env

networks:
  mern:
    driver: bridge
